export const FARE_CONFIG = {
  BASE_FARE: 1.5,
  PRICE_PER_MINUTE: 0.5,
  PRICE_PER_STOP_MINUTE: 0.2,
  COMMISSION_RATE: 10,
  MIN_FARE: 3.0,
  LOW_WALLET_THRESHOLD: 5.0,
  ADMIN_DAILY_TOPUP_LIMIT: 5000,
} as const;
